name: prts-sam
channels:
  - defaults
dependencies:
  - ca-certificates=2025.12.2=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.18=h543e019_0
  - pip=24.2=py38haa95532_0
  - python=3.8.20=h8205438_0
  - setuptools=75.1.0=py38haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - pip:
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - distinctipy==1.3.4
      - flatbuffers==25.12.19
      - fonttools==4.57.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.4
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==10.4.0
      - protobuf==5.29.5
      - pycocotools==2.0.7
      - pyparsing==3.1.4
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.15.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - requests==2.32.4
      - scikit-image==0.21.0
      - scipy==1.10.1
      - simplification==0.7.12
      - six==1.17.0
      - sympy==1.13.3
      - tifffile==2023.7.10
      - torch==1.12.1+cu116
      - torchaudio==0.12.1+cu116
      - torchvision==0.13.1+cu116
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - zipp==3.20.2
prefix: C:\Users\lanca\.conda\envs\prts-sam
